{% set version = "1.10.0" %}

package:
  name: holoviews
  version: {{ version }}

source:
  fn: holoviews-{{ version }}.tar.gz
  url: https://github.com/ioam/holoviews/archive/v{{version}}.tar.gz
  sha256: 52748165e60cba11ec0e6099fc9bf773fb7a19c28dae3a0f669496f4faa3c663

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt


requirements:
  build:
    - python
    - numpy
    - param
    - setuptools
  run:
    - python
    - param
    - numpy
    - matplotlib
    - bokeh
    - jupyter
    - notebook
    - ipython

test:
  imports:
    - holoviews

about:
  home: www.holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  license: BSD 3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
