{% set version = "1.12.2" %}

package:
  name: holoviews
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/holoviews/holoviews-{{ version }}.tar.gz
  sha256: 62004df8b60dff462b0e0b85506a357ba523f4b172819a2e8505992f95759444

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"
  entry_points:
    - holoviews = holoviews.util.command:main

requirements:
  host:
    - python
    - pip
    - param >=1.6.1,<2.0
  run:
    - python
    - param >=1.9.0,<2.0
    - numpy >=1.0
    - matplotlib >=2.1
    - bokeh >=1.1.0
    - jupyter
    - notebook
    - ipython >=5.4.0
    - pyviz_comms >=0.7.2

test:
  imports:
    - holoviews
  commands:
    - holoviews -h

about:
  home: www.holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  description: |
    HoloViews is an open-source Python library designed to make data analysis
    and visualization seamless and simple. With HoloViews, you can usually
    express what you want to do in very few lines of code, letting you focus on
    what you are trying to explore and convey, not on the process of plotting.
  license: BSD 3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/ioam/holoviews
  doc_url: http://holoviews.org/getting_started/index.html

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
