{% set version = "1.12.1" %}

package:
  name: holoviews
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/holoviews/holoviews-{{ version }}.tar.gz
  sha256: 86c198c443a85d7ae75e29cab086a82bd313c1b3d7583e5c8ea2d2d9f3c45624

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - holoviews = holoviews.util.command:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - param >=1.8.0,<2.0
    - numpy >=1.0
    - pyviz_comms >=0.7.2

test:
  imports:
    - holoviews
  commands:
    - holoviews -h

about:
  home: www.holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  description: |
    HoloViews is an open-source Python library designed to make data analysis
    and visualization seamless and simple. With HoloViews, you can usually
    express what you want to do in very few lines of code, letting you focus on
    what you are trying to explore and convey, not on the process of plotting.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/ioam/holoviews
  doc_url: http://holoviews.org/getting_started/index.html

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
