{% set version = "1.20.2" %}

package:
  name: holoviews
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/h/holoviews/holoviews-{{ version }}.tar.gz
  sha256: 8c78b798601ce3af31523667c6d1cb40df8d781249ebebbdb2c5f6143565e6d8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - holoviews = holoviews.util.command:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - bokeh >=3.1
    - colorcet
    - matplotlib-base >=3.0
    - numpy >=1.21
    - packaging
    - pandas >=1.3
    - panel >=1.0
    - param >=2.0,<3.0
    - pyviz_comms >=2.1

test:
  imports:
    - holoviews
  commands:
    - pip check
    - holoviews -h
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  description: |
    HoloViews is an open-source Python library designed to make data analysis
    and visualization seamless and simple. With HoloViews, you can usually
    express what you want to do in very few lines of code, letting you focus on
    what you are trying to explore and convey, not on the process of plotting.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/holoviz/holoviews
  doc_url: http://holoviews.org/getting_started/index.html

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
    - maximlt
    - hoxbro
