{% set version = "1.14.1" %}

package:
  name: holoviews
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/holoviews/holoviews-{{ version }}.tar.gz
  sha256: 9e5c45b87fd4dcebf29827adf8c7fedd7abcf0d30ba6324c89cda49031205d95

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - holoviews = holoviews.util.command:main

requirements:
  host:
    - python
    - pip
    - pyct
    - param >=1.6.1,<2.0
  run:
    - python
    - param >=1.9.3,<2.0
    - panel >=0.8.0
    - numpy >=1.0
    - pandas >=0.20.0
    - matplotlib-base >=2.2
    - bokeh >=1.1.0
    - notebook
    - colorcet
    - ipython >=5.4.0
    - pyviz_comms >=0.7.4

test:
  imports:
    - holoviews
  commands:
    - pip check
    - holoviews -h
  requires:
    - pip

about:
  home: www.holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  description: |
    HoloViews is an open-source Python library designed to make data analysis
    and visualization seamless and simple. With HoloViews, you can usually
    express what you want to do in very few lines of code, letting you focus on
    what you are trying to explore and convey, not on the process of plotting.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/ioam/holoviews
  doc_url: http://holoviews.org/getting_started/index.html

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
