{% set version = "1.10.5" %}

package:
  name: holoviews
  version: {{ version }}

source:
  fn: holoviews-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/holoviews/holoviews-{{ version }}.tar.gz
  sha256: 6470834430bfe80aa292c22edf0fa3d9744a1882ae2461cd4394b3eb246f2894

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .


requirements:
  build:
    - python
    - pip
    - param >=1.6.1,<2.0
  run:
    - python
    - param >=1.6.1,<2.0
    - numpy >=1.0
    - matplotlib >=2.1
    - bokeh >=0.12.15
    - jupyter
    - notebook
    - ipython >=5.4.0

test:
  imports:
    - holoviews

about:
  home: www.holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  license: BSD 3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
