{% set version = "1.15.3" %}

package:
  name: holoviews
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/holoviews/holoviews-{{ version }}.tar.gz
  sha256: a45891cd2b8fcd408742cffff351c928fbf4cf1ef7d1f04442c7d8786ee8e994

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - holoviews = holoviews.util.command:main

requirements:
  host:
    - python >=3.7
    - pip
    - pyct >=0.4.4
    - param >=1.7.0,<2.0
    - setuptools >=30.3.0
  run:
    - python >=3.7
    - param >=1.9.3,<2.0
    - panel >=0.13.1
    - numpy >=1.0
    - pandas >=0.20.0
    - matplotlib-base >=3.0
    - bokeh >=1.1.0,<3.0
    - colorcet
    - pyviz_comms >=0.7.4
    - packaging

test:
  imports:
    - holoviews
  commands:
    # - pip check 
    - holoviews -h
  requires:
    - pip

about:
  home: https://holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  description: |
    HoloViews is an open-source Python library designed to make data analysis
    and visualization seamless and simple. With HoloViews, you can usually
    express what you want to do in very few lines of code, letting you focus on
    what you are trying to explore and convey, not on the process of plotting.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/holoviz/holoviews
  doc_url: http://holoviews.org/getting_started/index.html

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
    - maximlt
