travis:
  secure:
    BINSTAR_TOKEN: jzBXuQN4N/l5mH3yFc8CsSVCO8JgkjKlfBu/7ilqeR19XZXDwGZBW6KHb5UneMLuXDMAKXzJOLNDWQ3+bdWbehZlYzkrgeLN5huH917F/eZBFqMrCosM/SxDmS0e0KpNQ4aVXRNBtbQEIoszl4sn6laaPmq6INmsVRl/u2vpPfvXTIkuwPAE/7lyCvfuY2ymcoVPLnfHs2CW86FFf2HPFOxgG8PafwnlbK37FQaX0NkcIu9fk2wu1iy/cbi0qlUQ+oYWdPFaPKD2Jqu/LN3pFvZkcnwg9GQXbCkZ1On59WOS9wxdn8wzVhu7bcM+RWUBD5d4cYWOpYCuKGeFPDEQus8F6oGweKgxiRl4JxFq6plP+LBoAZ8GEH/oaQKBBHt9Ia7bpuFhSu4G5nAqHi48CjwK1LDwTBaejMwEzr/8EC0j9z5lOk1KQcLRjRXlk1PGxTHgmmrG8YfxUyTN1/ISzEt+YBtveqT/gymLdzlbrS1LTbNrfpe0+pwQEBJg/LgyAegWtvd4dj/Jw+2kT77Qar+CE4+leF/eY1r3uIySnRoEJJiZAPzid/Ai2wUJC59uGeUd6ENmvS9vn8JlyyUm9fxQ4dbBLmtFlPYc+NyIfqQpr36WjTy346wHLavIdsldoclplkMCZQd5ZGFOf3jTYFWRIDAwSOkv555i4sl9S+Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4

channels:
  targets:
    - [conda-forge, dev]
